{{
  config(
    materialized='view',
    schema='marts'
  )
}}

-- Model: nbr_customers_one_order
-- Generated by: Agentic Analytics Agent
-- Source question: How many customers placed more than one order?
-- Description: Model answering: How many customers placed more than one order ?


WITH order_counts_per_customer AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT f.order_id)::numeric AS order_count
    FROM {{ ref('fact_order_items') }} f
    JOIN {{ ref('dim_customer') }} c
        ON f.customer_id = c.customer_id
    GROUP BY c.customer_unique_id
    HAVING COUNT(DISTINCT f.order_id) > 1
),

final AS (
    SELECT
        COUNT(*)::numeric AS repeat_customers
    FROM order_counts_per_customer
)

SELECT * FROM final

