{{
  config(
    materialized='table',
    schema='marts'
  )
}}

-- Model: revenue_by_category_2018
-- Generated by: Agentic Analytics Agent
-- Source question: Top 5 product categories by revenue in 2018?
-- Description: Model answering: Top 5 product categories by revenue in 2018? Fixed: replaced ORDER BY + LIMIT 5 anti-pattern with deterministic ROW_NUMBER() window function.


with order_items as (
    select
        order_id,
        product_id,
        date_id,
        order_status,
        revenue::numeric as revenue
    from {{ ref('fact_order_items') }}
    where order_status = 'delivered'
),

products as (
    select
        product_id,
        category_name
    from {{ ref('dim_product') }}
),

dates as (
    select
        date_id
    from {{ ref('dim_date') }}
    where year = 2018
),

joined as (
    select
        p.category_name,
        oi.order_id,
        oi.revenue
    from order_items oi
    inner join products p
        on oi.product_id = p.product_id
    inner join dates d
        on oi.date_id = d.date_id
),

aggregated as (
    select
        category_name,
        sum(revenue)::numeric                                as total_revenue,
        count(distinct order_id)::numeric                   as total_orders,
        (sum(revenue) / count(distinct order_id))::numeric  as avg_order_value
    from joined
    group by category_name
),

ranked as (
    select
        category_name,
        total_revenue,
        total_orders,
        avg_order_value,
        row_number() over (order by total_revenue desc)     as revenue_rank
    from aggregated
),

final as (
    select
        revenue_rank,
        category_name,
        total_revenue,
        total_orders,
        avg_order_value
    from ranked
    where revenue_rank <= 5
)

select * from final

