{{
  config(
    materialized='table',
    schema='marts'
  )
}}

-- Model: top_10_sellers_by_number_of_orders
-- Generated by: Agentic Analytics Agent
-- Source question: Top 10 sellers by number of orders?
-- Description: Model answering: Top 10 sellers by number of orders?

WITH seller_order_counts AS (
    SELECT
        s.seller_id,
        s.city AS seller_city,
        s.state AS seller_state,
        COUNT(DISTINCT f.order_id)::NUMERIC AS total_orders
    FROM {{ ref('fact_order_items') }} AS f
    INNER JOIN {{ ref('dim_seller') }} AS s
        ON f.seller_id = s.seller_id
    WHERE f.order_status = 'delivered'
    GROUP BY
        s.seller_id,
        s.city,
        s.state
),

final AS (
    SELECT
        seller_id,
        seller_city,
        seller_state,
        total_orders
    FROM seller_order_counts
    ORDER BY total_orders DESC
    LIMIT 10
)

SELECT
    seller_id,
    seller_city,
    seller_state,
    total_orders
FROM final

